version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dreamhomedb

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080