name: Dreamhome API

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and test
        run: |
          docker build -t dreamhome-api .

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dreamhome-api:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop dreamhome || true
            docker rm dreamhome || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/dreamhome-api:latest
            docker run -d -p --network:	db_default 5000:5000 --name dreamhome-api ${{ secrets.DOCKER_USERNAME }}/dreamhome-api:${{ github.sha }}
